//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /SSD1/Repositories/Unity/Heretical Solutions/Stanley Script Unity/Assets/Scripts/Stanley script/Grammars/StanleyParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace HereticalSolutions.StanleyScript.Grammars {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class StanleyParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SPACE=1, COMMENT=2, COMMENT_INPUT=3, LINE_COMMENT=4, REFER_TO=5, STORY=6, 
		SHOULD_BE=7, A=8, THE=9, AND=10, AT=11, AS=12, OF=13, TO=14, HAD=15, HAS=16, 
		HAVE=17, PASSED=18, WAS=19, WERE=20, CLOSIEST=21, FURTHEST=22, RANDOM=23, 
		STRONGEST=24, UNIQUE=25, WEAKEST=26, MINUTES=27, SECONDS=28, STAR=29, 
		DIVIDE=30, MODULE=31, PLUS=32, MINUS=33, EQUAL_SYMBOL=34, GREATER_SYMBOL=35, 
		LESS_SYMBOL=36, EXCLAMATION_SYMBOL=37, DOT=38, LR_BRACKET=39, RR_BRACKET=40, 
		COMMA=41, SEMI=42, AT_SIGN=43, ZERO_DECIMAL=44, ONE_DECIMAL=45, TWO_DECIMAL=46, 
		SINGLE_QUOTE_SYMB=47, DOUBLE_QUOTE_SYMB=48, REVERSE_QUOTE_SYMB=49, COLON_SYMB=50, 
		DOLLAR_SYMB=51, STRING_LITERAL=52, DECIMAL_LITERAL=53, REAL_LITERAL=54, 
		ID=55, REVERSE_QUOTE_ID=56, ERROR_RECONGNIGION=57;
	public const int
		RULE_script = 0, RULE_storyHeader = 1, RULE_statement = 2, RULE_defineStatement = 3, 
		RULE_defineSubject = 4, RULE_commandStatement = 5, RULE_timeStatement = 6, 
		RULE_actionStatement = 7, RULE_actionExpression = 8, RULE_actionWithArguments = 9, 
		RULE_objectArgument = 10, RULE_pluralSubjectsExpression = 11, RULE_subjectExpression = 12, 
		RULE_selectedSubject = 13, RULE_subjectSelectedByQuality = 14, RULE_subjectSelectedInRelation = 15, 
		RULE_pluralObjectsExpression = 16, RULE_objectExpression = 17, RULE_selectedObject = 18, 
		RULE_objectSelectedByQuality = 19, RULE_objectSelectedInRelation = 20, 
		RULE_selectionAdjective = 21, RULE_relativeSelectionAdjective = 22, RULE_assertAdjective = 23, 
		RULE_timeExpression = 24, RULE_timeStep = 25, RULE_subject = 26, RULE_object = 27, 
		RULE_action = 28, RULE_importVariableLiteral = 29, RULE_runtimeVariableLiteral = 30, 
		RULE_integer = 31, RULE_float = 32;
	public static readonly string[] ruleNames = {
		"script", "storyHeader", "statement", "defineStatement", "defineSubject", 
		"commandStatement", "timeStatement", "actionStatement", "actionExpression", 
		"actionWithArguments", "objectArgument", "pluralSubjectsExpression", "subjectExpression", 
		"selectedSubject", "subjectSelectedByQuality", "subjectSelectedInRelation", 
		"pluralObjectsExpression", "objectExpression", "selectedObject", "objectSelectedByQuality", 
		"objectSelectedInRelation", "selectionAdjective", "relativeSelectionAdjective", 
		"assertAdjective", "timeExpression", "timeStep", "subject", "object", 
		"action", "importVariableLiteral", "runtimeVariableLiteral", "integer", 
		"float"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, "'REFER TO'", "'STORY ABOUT'", "'SHOULD BE'", 
		"'A'", "'THE'", "'AND'", "'AT'", "'AS'", "'OF'", "'TO'", "'HAD'", "'HAS'", 
		"'HAVE'", "'PASSED'", "'WAS'", "'WERE'", "'CLOSIEST'", "'FURTHEST'", "'RANDOM'", 
		"'STRONGEST'", "'UNIQUE'", "'WEAKEST'", "'MINUTES'", "'SECONDS'", "'*'", 
		"'/'", "'%'", "'+'", "'-'", "'='", "'>'", "'<'", "'!'", "'.'", "'('", 
		"')'", "','", "';'", "'@'", "'0'", "'1'", "'2'", "'''", "'\"'", "'`'", 
		"':'", "'$'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SPACE", "COMMENT", "COMMENT_INPUT", "LINE_COMMENT", "REFER_TO", 
		"STORY", "SHOULD_BE", "A", "THE", "AND", "AT", "AS", "OF", "TO", "HAD", 
		"HAS", "HAVE", "PASSED", "WAS", "WERE", "CLOSIEST", "FURTHEST", "RANDOM", 
		"STRONGEST", "UNIQUE", "WEAKEST", "MINUTES", "SECONDS", "STAR", "DIVIDE", 
		"MODULE", "PLUS", "MINUS", "EQUAL_SYMBOL", "GREATER_SYMBOL", "LESS_SYMBOL", 
		"EXCLAMATION_SYMBOL", "DOT", "LR_BRACKET", "RR_BRACKET", "COMMA", "SEMI", 
		"AT_SIGN", "ZERO_DECIMAL", "ONE_DECIMAL", "TWO_DECIMAL", "SINGLE_QUOTE_SYMB", 
		"DOUBLE_QUOTE_SYMB", "REVERSE_QUOTE_SYMB", "COLON_SYMB", "DOLLAR_SYMB", 
		"STRING_LITERAL", "DECIMAL_LITERAL", "REAL_LITERAL", "ID", "REVERSE_QUOTE_ID", 
		"ERROR_RECONGNIGION"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "StanleyParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static StanleyParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public StanleyParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public StanleyParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ScriptContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StoryHeaderContext storyHeader() {
			return GetRuleContext<StoryHeaderContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ScriptContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_script; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScript(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScriptContext script() {
		ScriptContext _localctx = new ScriptContext(Context, State);
		EnterRule(_localctx, 0, RULE_script);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 66;
			storyHeader();
			State = 68;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 67;
				statement();
				}
				}
				State = 70;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 69805794224243488L) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StoryHeaderContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STORY() { return GetToken(StanleyParser.STORY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		public StoryHeaderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_storyHeader; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStoryHeader(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StoryHeaderContext storyHeader() {
		StoryHeaderContext _localctx = new StoryHeaderContext(Context, State);
		EnterRule(_localctx, 2, RULE_storyHeader);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 72;
			Match(STORY);
			State = 73;
			@object();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DefineStatementContext defineStatement() {
			return GetRuleContext<DefineStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CommandStatementContext commandStatement() {
			return GetRuleContext<CommandStatementContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 4, RULE_statement);
		try {
			State = 77;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case REFER_TO:
				EnterOuterAlt(_localctx, 1);
				{
				State = 75;
				defineStatement();
				}
				break;
			case A:
			case THE:
			case DOLLAR_SYMB:
			case STRING_LITERAL:
			case DECIMAL_LITERAL:
			case REAL_LITERAL:
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 76;
				commandStatement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefineStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REFER_TO() { return GetToken(StanleyParser.REFER_TO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DefineSubjectContext defineSubject() {
			return GetRuleContext<DefineSubjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AS() { return GetToken(StanleyParser.AS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		public DefineStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_defineStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefineStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefineStatementContext defineStatement() {
		DefineStatementContext _localctx = new DefineStatementContext(Context, State);
		EnterRule(_localctx, 6, RULE_defineStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79;
			Match(REFER_TO);
			State = 80;
			defineSubject();
			State = 81;
			Match(AS);
			State = 82;
			@object();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefineSubjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PluralSubjectsExpressionContext pluralSubjectsExpression() {
			return GetRuleContext<PluralSubjectsExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubjectExpressionContext subjectExpression() {
			return GetRuleContext<SubjectExpressionContext>(0);
		}
		public DefineSubjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_defineSubject; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDefineSubject(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefineSubjectContext defineSubject() {
		DefineSubjectContext _localctx = new DefineSubjectContext(Context, State);
		EnterRule(_localctx, 8, RULE_defineSubject);
		try {
			State = 86;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 84;
				pluralSubjectsExpression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 85;
				subjectExpression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionStatementContext actionStatement() {
			return GetRuleContext<ActionStatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TimeStatementContext timeStatement() {
			return GetRuleContext<TimeStatementContext>(0);
		}
		public CommandStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commandStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommandStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandStatementContext commandStatement() {
		CommandStatementContext _localctx = new CommandStatementContext(Context, State);
		EnterRule(_localctx, 10, RULE_commandStatement);
		try {
			State = 90;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case A:
			case THE:
			case DOLLAR_SYMB:
			case STRING_LITERAL:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 88;
				actionStatement();
				}
				break;
			case DECIMAL_LITERAL:
			case REAL_LITERAL:
				EnterOuterAlt(_localctx, 2);
				{
				State = 89;
				timeStatement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimeStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TimeExpressionContext[] timeExpression() {
			return GetRuleContexts<TimeExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TimeExpressionContext timeExpression(int i) {
			return GetRuleContext<TimeExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PASSED() { return GetToken(StanleyParser.PASSED, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] AND() { return GetTokens(StanleyParser.AND); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND(int i) {
			return GetToken(StanleyParser.AND, i);
		}
		public TimeStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_timeStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTimeStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TimeStatementContext timeStatement() {
		TimeStatementContext _localctx = new TimeStatementContext(Context, State);
		EnterRule(_localctx, 12, RULE_timeStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			timeExpression();
			State = 97;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==AND) {
				{
				{
				State = 93;
				Match(AND);
				State = 94;
				timeExpression();
				}
				}
				State = 99;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 100;
			Match(PASSED);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PluralSubjectsExpressionContext pluralSubjectsExpression() {
			return GetRuleContext<PluralSubjectsExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WERE() { return GetToken(StanleyParser.WERE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ActionExpressionContext actionExpression() {
			return GetRuleContext<ActionExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubjectExpressionContext subjectExpression() {
			return GetRuleContext<SubjectExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WAS() { return GetToken(StanleyParser.WAS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HAVE() { return GetToken(StanleyParser.HAVE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HAS() { return GetToken(StanleyParser.HAS, 0); }
		public ActionStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actionStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitActionStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionStatementContext actionStatement() {
		ActionStatementContext _localctx = new ActionStatementContext(Context, State);
		EnterRule(_localctx, 14, RULE_actionStatement);
		int _la;
		try {
			State = 118;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 102;
				pluralSubjectsExpression();
				State = 103;
				Match(WERE);
				State = 104;
				actionExpression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 106;
				subjectExpression();
				State = 107;
				Match(WAS);
				State = 108;
				actionExpression();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 110;
				pluralSubjectsExpression();
				State = 111;
				Match(HAVE);
				State = 112;
				actionExpression();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 114;
				subjectExpression();
				State = 115;
				_la = TokenStream.LA(1);
				if ( !(_la==HAS || _la==HAVE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 116;
				actionExpression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionWithArgumentsContext actionWithArguments() {
			return GetRuleContext<ActionWithArgumentsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		public ActionExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actionExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitActionExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionExpressionContext actionExpression() {
		ActionExpressionContext _localctx = new ActionExpressionContext(Context, State);
		EnterRule(_localctx, 16, RULE_actionExpression);
		try {
			State = 122;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 120;
				actionWithArguments();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 121;
				action();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionWithArgumentsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectArgumentContext objectArgument() {
			return GetRuleContext<ObjectArgumentContext>(0);
		}
		public ActionWithArgumentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actionWithArguments; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitActionWithArguments(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionWithArgumentsContext actionWithArguments() {
		ActionWithArgumentsContext _localctx = new ActionWithArgumentsContext(Context, State);
		EnterRule(_localctx, 18, RULE_actionWithArguments);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			action();
			State = 125;
			objectArgument();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectArgumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PluralObjectsExpressionContext pluralObjectsExpression() {
			return GetRuleContext<PluralObjectsExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TO() { return GetToken(StanleyParser.TO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AT() { return GetToken(StanleyParser.AT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ObjectExpressionContext objectExpression() {
			return GetRuleContext<ObjectExpressionContext>(0);
		}
		public ObjectArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_objectArgument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObjectArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjectArgumentContext objectArgument() {
		ObjectArgumentContext _localctx = new ObjectArgumentContext(Context, State);
		EnterRule(_localctx, 20, RULE_objectArgument);
		int _la;
		try {
			State = 135;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 128;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==AT || _la==TO) {
					{
					State = 127;
					_la = TokenStream.LA(1);
					if ( !(_la==AT || _la==TO) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
				}

				State = 130;
				pluralObjectsExpression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 132;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==AT || _la==TO) {
					{
					State = 131;
					_la = TokenStream.LA(1);
					if ( !(_la==AT || _la==TO) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
				}

				State = 134;
				objectExpression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PluralSubjectsExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SubjectContext[] subject() {
			return GetRuleContexts<SubjectContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubjectContext subject(int i) {
			return GetRuleContext<SubjectContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] AND() { return GetTokens(StanleyParser.AND); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND(int i) {
			return GetToken(StanleyParser.AND, i);
		}
		public PluralSubjectsExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pluralSubjectsExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPluralSubjectsExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PluralSubjectsExpressionContext pluralSubjectsExpression() {
		PluralSubjectsExpressionContext _localctx = new PluralSubjectsExpressionContext(Context, State);
		EnterRule(_localctx, 22, RULE_pluralSubjectsExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137;
			subject();
			State = 140;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 138;
				Match(AND);
				State = 139;
				subject();
				}
				}
				State = 142;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==AND );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubjectExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectedSubjectContext selectedSubject() {
			return GetRuleContext<SelectedSubjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubjectContext subject() {
			return GetRuleContext<SubjectContext>(0);
		}
		public SubjectExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_subjectExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubjectExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SubjectExpressionContext subjectExpression() {
		SubjectExpressionContext _localctx = new SubjectExpressionContext(Context, State);
		EnterRule(_localctx, 24, RULE_subjectExpression);
		try {
			State = 146;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case A:
			case THE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 144;
				selectedSubject();
				}
				break;
			case DOLLAR_SYMB:
			case STRING_LITERAL:
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 145;
				subject();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectedSubjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SubjectSelectedByQualityContext subjectSelectedByQuality() {
			return GetRuleContext<SubjectSelectedByQualityContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubjectSelectedInRelationContext subjectSelectedInRelation() {
			return GetRuleContext<SubjectSelectedInRelationContext>(0);
		}
		public SelectedSubjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selectedSubject; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelectedSubject(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectedSubjectContext selectedSubject() {
		SelectedSubjectContext _localctx = new SelectedSubjectContext(Context, State);
		EnterRule(_localctx, 26, RULE_selectedSubject);
		try {
			State = 150;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case A:
				EnterOuterAlt(_localctx, 1);
				{
				State = 148;
				subjectSelectedByQuality();
				}
				break;
			case THE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 149;
				subjectSelectedInRelation();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubjectSelectedByQualityContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode A() { return GetToken(StanleyParser.A, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SelectionAdjectiveContext selectionAdjective() {
			return GetRuleContext<SelectionAdjectiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OF() { return GetToken(StanleyParser.OF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SubjectContext subject() {
			return GetRuleContext<SubjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssertAdjectiveContext[] assertAdjective() {
			return GetRuleContexts<AssertAdjectiveContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssertAdjectiveContext assertAdjective(int i) {
			return GetRuleContext<AssertAdjectiveContext>(i);
		}
		public SubjectSelectedByQualityContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_subjectSelectedByQuality; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubjectSelectedByQuality(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SubjectSelectedByQualityContext subjectSelectedByQuality() {
		SubjectSelectedByQualityContext _localctx = new SubjectSelectedByQualityContext(Context, State);
		EnterRule(_localctx, 28, RULE_subjectSelectedByQuality);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152;
			Match(A);
			State = 153;
			selectionAdjective();
			State = 157;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ID) {
				{
				{
				State = 154;
				assertAdjective();
				}
				}
				State = 159;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 160;
			Match(OF);
			State = 161;
			subject();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubjectSelectedInRelationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode THE() { return GetToken(StanleyParser.THE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public RelativeSelectionAdjectiveContext relativeSelectionAdjective() {
			return GetRuleContext<RelativeSelectionAdjectiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TO() { return GetToken(StanleyParser.TO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SubjectExpressionContext subjectExpression() {
			return GetRuleContext<SubjectExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubjectContext subject() {
			return GetRuleContext<SubjectContext>(0);
		}
		public SubjectSelectedInRelationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_subjectSelectedInRelation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubjectSelectedInRelation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SubjectSelectedInRelationContext subjectSelectedInRelation() {
		SubjectSelectedInRelationContext _localctx = new SubjectSelectedInRelationContext(Context, State);
		EnterRule(_localctx, 30, RULE_subjectSelectedInRelation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 163;
			Match(THE);
			State = 164;
			relativeSelectionAdjective();
			State = 165;
			Match(TO);
			State = 166;
			subjectExpression();
			State = 167;
			subject();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PluralObjectsExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IntegerContext integer() {
			return GetRuleContext<IntegerContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FloatContext @float() {
			return GetRuleContext<FloatContext>(0);
		}
		public PluralObjectsExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pluralObjectsExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPluralObjectsExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PluralObjectsExpressionContext pluralObjectsExpression() {
		PluralObjectsExpressionContext _localctx = new PluralObjectsExpressionContext(Context, State);
		EnterRule(_localctx, 32, RULE_pluralObjectsExpression);
		try {
			State = 175;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DECIMAL_LITERAL:
				EnterOuterAlt(_localctx, 1);
				{
				State = 169;
				integer();
				State = 170;
				@object();
				}
				break;
			case REAL_LITERAL:
				EnterOuterAlt(_localctx, 2);
				{
				State = 172;
				@float();
				State = 173;
				@object();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SelectedObjectContext selectedObject() {
			return GetRuleContext<SelectedObjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		public ObjectExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_objectExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObjectExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjectExpressionContext objectExpression() {
		ObjectExpressionContext _localctx = new ObjectExpressionContext(Context, State);
		EnterRule(_localctx, 34, RULE_objectExpression);
		try {
			State = 179;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case A:
			case THE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 177;
				selectedObject();
				}
				break;
			case STRING_LITERAL:
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 178;
				@object();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectedObjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ObjectSelectedByQualityContext objectSelectedByQuality() {
			return GetRuleContext<ObjectSelectedByQualityContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectSelectedInRelationContext objectSelectedInRelation() {
			return GetRuleContext<ObjectSelectedInRelationContext>(0);
		}
		public SelectedObjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selectedObject; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelectedObject(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectedObjectContext selectedObject() {
		SelectedObjectContext _localctx = new SelectedObjectContext(Context, State);
		EnterRule(_localctx, 36, RULE_selectedObject);
		try {
			State = 183;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case A:
				EnterOuterAlt(_localctx, 1);
				{
				State = 181;
				objectSelectedByQuality();
				}
				break;
			case THE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 182;
				objectSelectedInRelation();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectSelectedByQualityContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode A() { return GetToken(StanleyParser.A, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SelectionAdjectiveContext selectionAdjective() {
			return GetRuleContext<SelectionAdjectiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OF() { return GetToken(StanleyParser.OF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssertAdjectiveContext[] assertAdjective() {
			return GetRuleContexts<AssertAdjectiveContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssertAdjectiveContext assertAdjective(int i) {
			return GetRuleContext<AssertAdjectiveContext>(i);
		}
		public ObjectSelectedByQualityContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_objectSelectedByQuality; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObjectSelectedByQuality(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjectSelectedByQualityContext objectSelectedByQuality() {
		ObjectSelectedByQualityContext _localctx = new ObjectSelectedByQualityContext(Context, State);
		EnterRule(_localctx, 38, RULE_objectSelectedByQuality);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 185;
			Match(A);
			State = 186;
			selectionAdjective();
			State = 190;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ID) {
				{
				{
				State = 187;
				assertAdjective();
				}
				}
				State = 192;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 193;
			Match(OF);
			State = 194;
			@object();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectSelectedInRelationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode THE() { return GetToken(StanleyParser.THE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public RelativeSelectionAdjectiveContext relativeSelectionAdjective() {
			return GetRuleContext<RelativeSelectionAdjectiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TO() { return GetToken(StanleyParser.TO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public SubjectExpressionContext subjectExpression() {
			return GetRuleContext<SubjectExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		public ObjectSelectedInRelationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_objectSelectedInRelation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObjectSelectedInRelation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjectSelectedInRelationContext objectSelectedInRelation() {
		ObjectSelectedInRelationContext _localctx = new ObjectSelectedInRelationContext(Context, State);
		EnterRule(_localctx, 40, RULE_objectSelectedInRelation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 196;
			Match(THE);
			State = 197;
			relativeSelectionAdjective();
			State = 198;
			Match(TO);
			State = 199;
			subjectExpression();
			State = 200;
			@object();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectionAdjectiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(StanleyParser.ID, 0); }
		public SelectionAdjectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selectionAdjective; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelectionAdjective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectionAdjectiveContext selectionAdjective() {
		SelectionAdjectiveContext _localctx = new SelectionAdjectiveContext(Context, State);
		EnterRule(_localctx, 42, RULE_selectionAdjective);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 202;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelativeSelectionAdjectiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(StanleyParser.ID, 0); }
		public RelativeSelectionAdjectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relativeSelectionAdjective; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelativeSelectionAdjective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelativeSelectionAdjectiveContext relativeSelectionAdjective() {
		RelativeSelectionAdjectiveContext _localctx = new RelativeSelectionAdjectiveContext(Context, State);
		EnterRule(_localctx, 44, RULE_relativeSelectionAdjective);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 204;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssertAdjectiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(StanleyParser.ID, 0); }
		public AssertAdjectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assertAdjective; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssertAdjective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssertAdjectiveContext assertAdjective() {
		AssertAdjectiveContext _localctx = new AssertAdjectiveContext(Context, State);
		EnterRule(_localctx, 46, RULE_assertAdjective);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 206;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimeExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TimeStepContext timeStep() {
			return GetRuleContext<TimeStepContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IntegerContext integer() {
			return GetRuleContext<IntegerContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FloatContext @float() {
			return GetRuleContext<FloatContext>(0);
		}
		public TimeExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_timeExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTimeExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TimeExpressionContext timeExpression() {
		TimeExpressionContext _localctx = new TimeExpressionContext(Context, State);
		EnterRule(_localctx, 48, RULE_timeExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 210;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DECIMAL_LITERAL:
				{
				State = 208;
				integer();
				}
				break;
			case REAL_LITERAL:
				{
				State = 209;
				@float();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 212;
			timeStep();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimeStepContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SECONDS() { return GetToken(StanleyParser.SECONDS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUTES() { return GetToken(StanleyParser.MINUTES, 0); }
		public TimeStepContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_timeStep; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTimeStep(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TimeStepContext timeStep() {
		TimeStepContext _localctx = new TimeStepContext(Context, State);
		EnterRule(_localctx, 50, RULE_timeStep);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 214;
			_la = TokenStream.LA(1);
			if ( !(_la==MINUTES || _la==SECONDS) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ImportVariableLiteralContext importVariableLiteral() {
			return GetRuleContext<ImportVariableLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RuntimeVariableLiteralContext runtimeVariableLiteral() {
			return GetRuleContext<RuntimeVariableLiteralContext>(0);
		}
		public SubjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_subject; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubject(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SubjectContext subject() {
		SubjectContext _localctx = new SubjectContext(Context, State);
		EnterRule(_localctx, 52, RULE_subject);
		try {
			State = 218;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DOLLAR_SYMB:
				EnterOuterAlt(_localctx, 1);
				{
				State = 216;
				importVariableLiteral();
				}
				break;
			case STRING_LITERAL:
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 217;
				runtimeVariableLiteral();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(StanleyParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(StanleyParser.STRING_LITERAL, 0); }
		public ObjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_object; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObject(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjectContext @object() {
		ObjectContext _localctx = new ObjectContext(Context, State);
		EnterRule(_localctx, 54, RULE_object);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 220;
			_la = TokenStream.LA(1);
			if ( !(_la==STRING_LITERAL || _la==ID) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(StanleyParser.ID, 0); }
		public ActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_action; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionContext action() {
		ActionContext _localctx = new ActionContext(Context, State);
		EnterRule(_localctx, 56, RULE_action);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 222;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImportVariableLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOLLAR_SYMB() { return GetToken(StanleyParser.DOLLAR_SYMB, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(StanleyParser.ID, 0); }
		public ImportVariableLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_importVariableLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImportVariableLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImportVariableLiteralContext importVariableLiteral() {
		ImportVariableLiteralContext _localctx = new ImportVariableLiteralContext(Context, State);
		EnterRule(_localctx, 58, RULE_importVariableLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 224;
			Match(DOLLAR_SYMB);
			State = 225;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RuntimeVariableLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(StanleyParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(StanleyParser.STRING_LITERAL, 0); }
		public RuntimeVariableLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_runtimeVariableLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRuntimeVariableLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RuntimeVariableLiteralContext runtimeVariableLiteral() {
		RuntimeVariableLiteralContext _localctx = new RuntimeVariableLiteralContext(Context, State);
		EnterRule(_localctx, 60, RULE_runtimeVariableLiteral);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 227;
			_la = TokenStream.LA(1);
			if ( !(_la==STRING_LITERAL || _la==ID) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IntegerContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL_LITERAL() { return GetToken(StanleyParser.DECIMAL_LITERAL, 0); }
		public IntegerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_integer; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInteger(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntegerContext integer() {
		IntegerContext _localctx = new IntegerContext(Context, State);
		EnterRule(_localctx, 62, RULE_integer);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 229;
			Match(DECIMAL_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FloatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REAL_LITERAL() { return GetToken(StanleyParser.REAL_LITERAL, 0); }
		public FloatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_float; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IStanleyParserVisitor<TResult> typedVisitor = visitor as IStanleyParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFloat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FloatContext @float() {
		FloatContext _localctx = new FloatContext(Context, State);
		EnterRule(_localctx, 64, RULE_float);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 231;
			Match(REAL_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,57,234,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,1,0,1,0,4,0,69,8,0,11,0,12,0,70,
		1,1,1,1,1,1,1,2,1,2,3,2,78,8,2,1,3,1,3,1,3,1,3,1,3,1,4,1,4,3,4,87,8,4,
		1,5,1,5,3,5,91,8,5,1,6,1,6,1,6,5,6,96,8,6,10,6,12,6,99,9,6,1,6,1,6,1,7,
		1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,3,7,119,8,
		7,1,8,1,8,3,8,123,8,8,1,9,1,9,1,9,1,10,3,10,129,8,10,1,10,1,10,3,10,133,
		8,10,1,10,3,10,136,8,10,1,11,1,11,1,11,4,11,141,8,11,11,11,12,11,142,1,
		12,1,12,3,12,147,8,12,1,13,1,13,3,13,151,8,13,1,14,1,14,1,14,5,14,156,
		8,14,10,14,12,14,159,9,14,1,14,1,14,1,14,1,15,1,15,1,15,1,15,1,15,1,15,
		1,16,1,16,1,16,1,16,1,16,1,16,3,16,176,8,16,1,17,1,17,3,17,180,8,17,1,
		18,1,18,3,18,184,8,18,1,19,1,19,1,19,5,19,189,8,19,10,19,12,19,192,9,19,
		1,19,1,19,1,19,1,20,1,20,1,20,1,20,1,20,1,20,1,21,1,21,1,22,1,22,1,23,
		1,23,1,24,1,24,3,24,211,8,24,1,24,1,24,1,25,1,25,1,26,1,26,3,26,219,8,
		26,1,27,1,27,1,28,1,28,1,29,1,29,1,29,1,30,1,30,1,31,1,31,1,32,1,32,1,
		32,0,0,33,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,
		44,46,48,50,52,54,56,58,60,62,64,0,4,1,0,16,17,2,0,11,11,14,14,1,0,27,
		28,2,0,52,52,55,55,222,0,66,1,0,0,0,2,72,1,0,0,0,4,77,1,0,0,0,6,79,1,0,
		0,0,8,86,1,0,0,0,10,90,1,0,0,0,12,92,1,0,0,0,14,118,1,0,0,0,16,122,1,0,
		0,0,18,124,1,0,0,0,20,135,1,0,0,0,22,137,1,0,0,0,24,146,1,0,0,0,26,150,
		1,0,0,0,28,152,1,0,0,0,30,163,1,0,0,0,32,175,1,0,0,0,34,179,1,0,0,0,36,
		183,1,0,0,0,38,185,1,0,0,0,40,196,1,0,0,0,42,202,1,0,0,0,44,204,1,0,0,
		0,46,206,1,0,0,0,48,210,1,0,0,0,50,214,1,0,0,0,52,218,1,0,0,0,54,220,1,
		0,0,0,56,222,1,0,0,0,58,224,1,0,0,0,60,227,1,0,0,0,62,229,1,0,0,0,64,231,
		1,0,0,0,66,68,3,2,1,0,67,69,3,4,2,0,68,67,1,0,0,0,69,70,1,0,0,0,70,68,
		1,0,0,0,70,71,1,0,0,0,71,1,1,0,0,0,72,73,5,6,0,0,73,74,3,54,27,0,74,3,
		1,0,0,0,75,78,3,6,3,0,76,78,3,10,5,0,77,75,1,0,0,0,77,76,1,0,0,0,78,5,
		1,0,0,0,79,80,5,5,0,0,80,81,3,8,4,0,81,82,5,12,0,0,82,83,3,54,27,0,83,
		7,1,0,0,0,84,87,3,22,11,0,85,87,3,24,12,0,86,84,1,0,0,0,86,85,1,0,0,0,
		87,9,1,0,0,0,88,91,3,14,7,0,89,91,3,12,6,0,90,88,1,0,0,0,90,89,1,0,0,0,
		91,11,1,0,0,0,92,97,3,48,24,0,93,94,5,10,0,0,94,96,3,48,24,0,95,93,1,0,
		0,0,96,99,1,0,0,0,97,95,1,0,0,0,97,98,1,0,0,0,98,100,1,0,0,0,99,97,1,0,
		0,0,100,101,5,18,0,0,101,13,1,0,0,0,102,103,3,22,11,0,103,104,5,20,0,0,
		104,105,3,16,8,0,105,119,1,0,0,0,106,107,3,24,12,0,107,108,5,19,0,0,108,
		109,3,16,8,0,109,119,1,0,0,0,110,111,3,22,11,0,111,112,5,17,0,0,112,113,
		3,16,8,0,113,119,1,0,0,0,114,115,3,24,12,0,115,116,7,0,0,0,116,117,3,16,
		8,0,117,119,1,0,0,0,118,102,1,0,0,0,118,106,1,0,0,0,118,110,1,0,0,0,118,
		114,1,0,0,0,119,15,1,0,0,0,120,123,3,18,9,0,121,123,3,56,28,0,122,120,
		1,0,0,0,122,121,1,0,0,0,123,17,1,0,0,0,124,125,3,56,28,0,125,126,3,20,
		10,0,126,19,1,0,0,0,127,129,7,1,0,0,128,127,1,0,0,0,128,129,1,0,0,0,129,
		130,1,0,0,0,130,136,3,32,16,0,131,133,7,1,0,0,132,131,1,0,0,0,132,133,
		1,0,0,0,133,134,1,0,0,0,134,136,3,34,17,0,135,128,1,0,0,0,135,132,1,0,
		0,0,136,21,1,0,0,0,137,140,3,52,26,0,138,139,5,10,0,0,139,141,3,52,26,
		0,140,138,1,0,0,0,141,142,1,0,0,0,142,140,1,0,0,0,142,143,1,0,0,0,143,
		23,1,0,0,0,144,147,3,26,13,0,145,147,3,52,26,0,146,144,1,0,0,0,146,145,
		1,0,0,0,147,25,1,0,0,0,148,151,3,28,14,0,149,151,3,30,15,0,150,148,1,0,
		0,0,150,149,1,0,0,0,151,27,1,0,0,0,152,153,5,8,0,0,153,157,3,42,21,0,154,
		156,3,46,23,0,155,154,1,0,0,0,156,159,1,0,0,0,157,155,1,0,0,0,157,158,
		1,0,0,0,158,160,1,0,0,0,159,157,1,0,0,0,160,161,5,13,0,0,161,162,3,52,
		26,0,162,29,1,0,0,0,163,164,5,9,0,0,164,165,3,44,22,0,165,166,5,14,0,0,
		166,167,3,24,12,0,167,168,3,52,26,0,168,31,1,0,0,0,169,170,3,62,31,0,170,
		171,3,54,27,0,171,176,1,0,0,0,172,173,3,64,32,0,173,174,3,54,27,0,174,
		176,1,0,0,0,175,169,1,0,0,0,175,172,1,0,0,0,176,33,1,0,0,0,177,180,3,36,
		18,0,178,180,3,54,27,0,179,177,1,0,0,0,179,178,1,0,0,0,180,35,1,0,0,0,
		181,184,3,38,19,0,182,184,3,40,20,0,183,181,1,0,0,0,183,182,1,0,0,0,184,
		37,1,0,0,0,185,186,5,8,0,0,186,190,3,42,21,0,187,189,3,46,23,0,188,187,
		1,0,0,0,189,192,1,0,0,0,190,188,1,0,0,0,190,191,1,0,0,0,191,193,1,0,0,
		0,192,190,1,0,0,0,193,194,5,13,0,0,194,195,3,54,27,0,195,39,1,0,0,0,196,
		197,5,9,0,0,197,198,3,44,22,0,198,199,5,14,0,0,199,200,3,24,12,0,200,201,
		3,54,27,0,201,41,1,0,0,0,202,203,5,55,0,0,203,43,1,0,0,0,204,205,5,55,
		0,0,205,45,1,0,0,0,206,207,5,55,0,0,207,47,1,0,0,0,208,211,3,62,31,0,209,
		211,3,64,32,0,210,208,1,0,0,0,210,209,1,0,0,0,211,212,1,0,0,0,212,213,
		3,50,25,0,213,49,1,0,0,0,214,215,7,2,0,0,215,51,1,0,0,0,216,219,3,58,29,
		0,217,219,3,60,30,0,218,216,1,0,0,0,218,217,1,0,0,0,219,53,1,0,0,0,220,
		221,7,3,0,0,221,55,1,0,0,0,222,223,5,55,0,0,223,57,1,0,0,0,224,225,5,51,
		0,0,225,226,5,55,0,0,226,59,1,0,0,0,227,228,7,3,0,0,228,61,1,0,0,0,229,
		230,5,53,0,0,230,63,1,0,0,0,231,232,5,54,0,0,232,65,1,0,0,0,20,70,77,86,
		90,97,118,122,128,132,135,142,146,150,157,175,179,183,190,210,218
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace HereticalSolutions.StanleyScript.Grammars
